### PR TITLE
Update badge on README

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@frautaso r+

**Comment by frautaso** [comment]
:pushpin: Commit 8e02c5b08c1576333aa665c47a141bc0a9069ffc has been approved by `JohnTitor`

**Comment by frautaso** [comment]
:hourglass: 8e02c5b08c1576333aa665c47a141bc0a9069ffc has been merged into the auto branch f37c9edeafcad28a4bd10cf84cc1c9c72ff4e988

**Comment by frautaso** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
