### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by JohnTitor**
Use `go-github v28` and run `go get -u && go mod tidy`

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
@frautaso r+

**Comment by frautaso** [comment]
:pushpin: Commit 1abda274e1b200c0fc6e4a17025fc3d5e35b3d0e has been approved by `JohnTitor`

**Comment by frautaso** [comment]
:hourglass: 1abda274e1b200c0fc6e4a17025fc3d5e35b3d0e has been merged into the auto branch 3b7cca67a2f9919eb5cf329b20568c4bff4c4b9c

**Comment by frautaso** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
